# Boolean Indexing, Set Operations, and Sorting

   ##                                 Boolean indexing

In [3]:
import numpy as np
# We create a 5 x 5 ndarray that contains integers from 0 to 24
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()

# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()


Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



In [2]:
X > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## Set operations and comparing two arrays

In [5]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('The elements that are in y that are not in x:', np.setdiff1d(y,x))
print('All the elements of x and y:',np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
The elements that are in y that are not in x: [6 7 8]
All the elements of x and y: [1 2 3 4 5 6 7 8]


## Sorting using sort function

In [8]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,12,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))

# When we sort out of place the original array remains intact. To see this we print x again
print()
print('x after sorting:', x)




Original x =  [10  9  5  1  9  9  5  2  3  3]

Sorted x (out of place): [ 1  2  3  3  5  5  9  9  9 10]

x after sorting: [10  9  5  1  9  9  5  2  3  3]


## keeping only unique elements after sorting

In [34]:
print()
print('Original x = ', x)

# We sort x but only keep the unique elements in x
print()
print("Sorted unique elements of X=", np.sort(np.unique(x)))


Original x =  [ 5  1  3  9 10  9  7  6  5  2]

Sorted unique elements of X= [ 1  2  3  5  6  7  9 10]


## Sorting using sort method

In [35]:
# We create an unsorted rank 1 ndarray
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a method.
x.sort()

# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after sorting:', x)


Original x =  [9 4 7 2 5 9 7 8 3 4]

x after sorting: [2 3 4 4 5 7 7 8 9 9]


# Sorting 2D array by columns and rows

In [39]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 5  4  6  6  8]
 [ 2  7  5  3  7]
 [ 1  1  7  2  3]
 [10  8  6  6  1]
 [ 3  8 10  9  6]]


X with sorted columns :
 [[ 1  1  5  2  1]
 [ 2  4  6  3  3]
 [ 3  7  6  6  6]
 [ 5  8  7  6  7]
 [10  8 10  9  8]]

X with sorted rows :
 [[ 4  5  6  6  8]
 [ 2  3  5  7  7]
 [ 1  1  2  3  7]
 [ 1  6  6  8 10]
 [ 3  6  8  9 10]]


## Numpy_quiz_Manipulating_ndarrays

In [20]:
import numpy as np

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1,26).reshape(5,5)
#X
# Use Boolean indexing to pick out only the odd numbers in the array
Y = X%2 !=0
Y

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])