# How to generate numpy array from nothing ?

## generate 2D zeros Array

In [1]:
import numpy as np
# We create a 3 x 4 ndarray full of zeros. 
X = np.zeros((3,4))

# We print X
print('X =\n', X)
print("\n")

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X =
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


## generate 2D ones Array

In [2]:
# We create a 3 x 2 ndarray full of ones. 
X = np.ones((3,2))

# We print X

print('X = \n', X)
print("\n")

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


## generate array with full function

In [3]:
# We create a 2 x 3 ndarray full of fives. 
X = np.full((2,3), 5) 

# We print X
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)

X = 
 [[5 5 5]
 [5 5 5]]


X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32


## generate Identity matrix

In [4]:
# We create a 5 x 5 Identity matrix. 
X = np.eye(5)

# We print X
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype) 

X = 
 [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]


X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


## generate diagonal matrix

In [6]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50
# on its main diagonal
X = np.diag([10,20,30,50])

# We print X
print('X = \n', X)
print('\n')

X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]




## generate 1D array using arrange function

In [7]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [0 1 2 3 4 5 6 7 8 9]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [8]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9. 
x = np.arange(4,10)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [4 5 6 7 8 9]


x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [9]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
x = np.arange(1,14,3)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [ 1  4  7 10 13]


x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [11]:
# We create a rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 0.3.
x = np.arange(1,14,0.3)

# We print the ndarray
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [  1.    1.3   1.6   1.9   2.2   2.5   2.8   3.1   3.4   3.7   4.    4.3
   4.6   4.9   5.2   5.5   5.8   6.1   6.4   6.7   7.    7.3   7.6   7.9
   8.2   8.5   8.8   9.1   9.4   9.7  10.   10.3  10.6  10.9  11.2  11.5
  11.8  12.1  12.4  12.7  13.   13.3  13.6  13.9]


x has dimensions: (44,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


## generate 1D aaray by using linspace function

In [12]:
import numpy as np
x=np.linspace(0,25,10)
# step= (sotp-start)/(N-1)
# step= (25-0)/(10-1)

print('x = \n', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype) 

x = 
 [  0.           2.77777778   5.55555556   8.33333333  11.11111111
  13.88888889  16.66666667  19.44444444  22.22222222  25.        ]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [13]:
x=np.linspace(5,63,10,endpoint=False)
# step=(stop-start)/N
# step=(63-5)/10
print('x = ', x)
print('\n')

# We print information about the ndarray
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)

x =  [  5.   10.8  16.6  22.4  28.2  34.   39.8  45.6  51.4  57.2]


x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


## How t reshape an aranged 1D array to 2D array  ?

In [14]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print('\n')
print('Original x = ', x)
print('\n')

# We reshape x into a 4 x 5 ndarray 
x = np.reshape(x, (4,5))

# We print the reshaped x
print('\n')
print('Reshaped x = \n', x)
print('\n')

# We print information about the reshaped x
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)



Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]




Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [15]:
# We create a a rank 1 ndarray with sequential integers from 0 to 19 and
# reshape it to a 4 x 5 array 
Y = np.arange(20).reshape(4, 5)

# We print Y
print()
print('Y = \n', Y)
print()

# We print information about Y
print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype) 


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int32


## How t reshape linspace 1D array  to 2D array?

In [17]:
# We create a rank 1 ndarray with 10 integers evenly spaced between 0 and 50,
# with 50 excluded. We then reshape it to a 5 x 2 ndarray
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

# We print X
print('\n')
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)



X = 
 [[  0.   5.]
 [ 10.  15.]
 [ 20.  25.]
 [ 30.  35.]
 [ 40.  45.]]


X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


## create random array

In [19]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
import numpy as np
X = np.random.random(size=(3,3))

# We print X
print('\n')
print('X = \n', X)
print('\n')

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)



X = 
 [[ 0.56111797  0.51458904  0.81087862]
 [ 0.61872198  0.69781139  0.91813858]
 [ 0.88406782  0.35871933  0.5363763 ]]


X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [23]:
# We create a 3 x 2 ndarray with random integers in the half-open interval [4, 15).
X = np.random.randint(4,15,size=(3,2))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[12 14]
 [ 9  9]
 [13  5]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32



# Create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution

In [26]:
import numpy as np
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
X = np.random.normal(0, 0.1, size=(1000,1000))

# We print X
print()
print('X = \n', X)
print()

# We print information about X
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The elements in X have a standard deviation of:', X.std())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')
(X > 0).sum()


X = 
 [[-0.18092989 -0.00585332  0.04219675 ..., -0.00808388 -0.07460634
  -0.10496239]
 [-0.0520014  -0.10064221  0.08122733 ...,  0.03128112  0.01648933
   0.06177576]
 [-0.07513305  0.11179007  0.1863216  ...,  0.16245715 -0.21131035
  -0.11072666]
 ..., 
 [-0.10586579 -0.03404232 -0.27416686 ..., -0.06631062  0.10247771
   0.03152669]
 [-0.0215483   0.17014092  0.00189935 ..., -0.10241139  0.2059653
  -0.04670221]
 [-0.02840922 -0.02281114  0.03582503 ..., -0.16929512 -0.06087864
   0.09443111]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: -8.42308645941e-05
The elements in X have a standard deviation of: 0.10002814182
The maximum value in X is: 0.492269109367
The minimum value in X is: -0.525417063449
X has 500138 negative numbers
X has 499862 positive numbers


499862

# question :

In [28]:
import numpy as np

# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X=np.arange(2,33,2).reshape(4,4)
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [29]:
X=np.linspace(2,32,16).reshape(4,4)
X

array([[  2.,   4.,   6.,   8.],
       [ 10.,  12.,  14.,  16.],
       [ 18.,  20.,  22.,  24.],
       [ 26.,  28.,  30.,  32.]])