In [1]:
import numpy as np

X = np.arange(1,26).reshape(5,5)

Y = X[X % 2 != 0]
print("X=",X)
print()
print('Y=',Y)

X= [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Y= [ 1  3  5  7  9 11 13 15 17 19 21 23 25]
